language: ruby
rvm:
- 2.1
sudo: false
script:
- rake test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: dl3uWpiNWF9R81lzeOSe2G4e2+se+pUVEFKIiPfT9kvOQ733K+mw1ULb4VK6IsQ8Flkb3nDQRq78cZCYswAizwOlTyiYnFVSz8eTEYIGBPbFf1+yi/6jXlAMRhMI/hy2zSnAAvNYM/F5Ixzy7y93Iv6hkj+mz3ObfUImLvCwUnY=
  - secure: wLT+Sr2WYXfTZgwYo6jnlg7FKYu3yBjiwmv0XvwMIaqRWO/Y6QGc83J9FtGGdIsrKYA6T1h8iXhzCgcwNn1lzro4kIhTdjCnGZ5C4+R/EwfuBgye444ICp6qonvXjxZre31j1vEXCt/biw9C3eErCUkKTj3VX01SdCE/8ED7jTU=
deploy:
  provider: s3
  access_key_id: AKIAJUHCKKZCTVJQGOXA
  secret_access_key:
    secure: JqgqPebaI6aoplctpz3y6baGbi9PEjv8MLZWb/fXPWIWmq1jHfU/mLM5gUAT0N41qqcKT9JtrUD5ybG8EyKaczt/z5CHUR+K0DkVVc0wiKiM5+Ow+XAK40ZamZj+pRgHy8hhPLqcVjuZp1DEzM6MgfJ7RQ7n7AJXbdRlal511Ug=
  bucket: www.jacobtomlinson.co.uk
  local-dir: _site
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  on:
    repo: jacobtomlinson/jacobtomlinson.github.io
    branch: master
  after_success:
    - rake purge
