# Site settings
title: Jacob Tomlinson | Tech Blog
email: jacob@jacobtomlinson.co.uk
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://www.jacobtomlinson.co.uk"
author_name: Jacob Tomlinson
author_description: A unix system administrator by day and a website and app developer by night. With experience in RHEL and OS X administration, HTML5, CSS3, JavaScript, jQuery, PHP, Python, MySQL, CodeIgniter, Wordpress and much more. When he is not tapping away at his keyboard you can usually find him making music, gaming or spending time with his wonderful fianc&#233;e.
twitter_username: _jacobtomlinson
github_username:  jacobtomlinson
google_plus_link: https://plus.google.com/+JacobTomlinson0/
google_analytics: UA-20365477-2
disqus_development_account: wwwdevjacobtomlinsoncouk
disqus_production_account: jacobtomlinson

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
